# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Michel Fernandes
tagline:             'Solutions Architect'
description:         'Um pouco sobre Java, Python e C# aplicados a Machine Learning e Chatbots.'
url:                 
baseurl:             'michelpf.github.io'
paginate:            5

# About/contact
author:
  name:              Michel Fernandes
  url:               https://twitter.com/michelpf
  email:             michelpf@gmail.com

# Custom vars
version:             1.0.0
